version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - docker login aihara.jfrog.io -u ${JFROG_USER_NAME} -p ${JFROG_PASS}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - IMAGE_TAG=$(git rev-parse --short HEAD)
      - docker tag ${IMAGE_REPO_NAME}:latest aihara.jfrog.io/aihara-test-ocker/${DOCKER_REPOSITORY}:${IMAGE_TAG}
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push aihara.jfrog.io/aihara-test-docker/${DOCKER_REPOSITORY}:${IMAGE_TAG}
